GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWlra28iLCJpYXQiOjE2NDY4MjY4NDN9.enODl3GWvMl_Vrq0uB9jezX5KFDWqa_ZCe-PlmB8thQ
###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "mikko"
}


###
GET http://localhost:3002/users

###
POST http://localhost:3002/users
Content-Type: application/json

{
    "name": "Mikko",
    "password": "password"
}

###
GET http://localhost:3002/users

###
POST http://localhost:3002/users/login
Content-Type: application/json

{
    "name": "Mikko",
    "password": "password"
}